version: '2'

services:
  frontend:
    build:
      context: ./
      dockerfile: dockerfile-frontend
    depends_on:
      - backend
    ports:
      - "4200:4200"
    volumes:
      - ../frontend:/home/node/medical-expenses/frontend

  backend:
    build:
      context: ./
      dockerfile: dockerfile-backend
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/home/node/medical-expenses/backend
